[project]
name = "web"
version = "0.1.0"
description = ""
authors = [
    {name = "Lautaro Budini",email = "lautarobudini5@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "flask (>=3.1.2,<4.0.0)",
    "flask-sqlalchemy-lite (>=0.1.0,<0.2.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "geoalchemy2 (>=0.18.0,<0.19.0)",
    "shapely (>=2.0.0,<3.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)",
    "flask-session (>=0.8.0,<0.9.0)",
    "flask-cors (>=6.0.1,<7.0.0)"
]

[tool.poetry]
packages = [{include = "web", from = "src"}]


[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
